env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
  - eslint:recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - @typescript-eslint
  - react-hooks
rules: {
  eqeqeq: error,
  no-debugger: error,
  no-unused-vars: error,
  no-duplicate-imports: error,
  no-multiple-empty-lines: error,
  exhaustive-deps: off,
  react-hooks/exhaustive-deps: off,
}
